 theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - CODE_OF_CONDUCT.md
logo: https://user-images.githubusercontent.com/66209958/91997608-e9487900-ed57-11ea-8bf6-4dbc1ed42f0c.png
