site_name: wappdriver

theme:
  name: material
  navigation_depth: 4
  icon: 
    repo: fontawesome/brands/github

site_url: https://github.com/aahnik/wappdriver/
markdown_extensions:
  - admonition
nav:
  - Getting Started: index.md
  - Setup: usage/01_first_time_setup.md
  - Sending Messages: usage/02_sending_messages.md
  - Sending Files: usage/03_sending_files.md
  - Advanced: usage/04_advanced.md
  - Developers: For_Developers.md
  - Concepts: concepts.md
  - Help: help.md

repo_url: https://github.com/aahnik/wappdriver
edit_uri: ""


