blank_issues_enabled: true
contact_links:
  - name: Read Latest Article on Medium
    url: https://medium.com/@aahnikdaw/how-to-send-a-whatsapp-message-reliably-in-only-3-lines-of-code-python-53201e9c09f3
    about: How to send WhatsApp messages for free and reliably with only 3 lines of code? Python
